### ISSUE TITLE
India is not support by that provider

### ISSUE THREAD

**Issue by varundeva** [machine1337/fake-sms#12]
Getting errors that some countries do not support
Otherwise, it's a good script.
thanks

**Comment by machine1337** [comment]
@varundeva  yes asians are not supported

**Comment by mekb-turtle** [comment]
racist

textbelt is what this tool uses, the owner of this repo doesn't give credit or tell, this is just an awful wrapper for it

**Comment by varundeva** [comment]
Yes.
Can be used for reference.
Will not work actually.
Instead of that we can change sms gateway i think
