### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ChayimEliazer** [machine1337/fake-sms#18]
Not working. And where is the run.sh file ? there is no such file to begin with that everyone says to run ./run.sh

**Comment by machine1337** [comment]
@ChayimEliazer Read the installation Instructions Carefully....

**Comment by ChayimEliazer** [comment]
I read carefully Did everything instructed, and then came the error when using command in phase C:
 pip install requirements.txt 
Error:
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
HINT: You are attempting to install a package literally named "requirements.txt" (which cannot exist). Consider using the '-r' flag to install the packages listed in requirements.txt
ERROR: No matching distribution found for requirements.txt

Then tried installing manually:
pip install termcolor
pip install requests
And it got intalled, then I entered python fakesms.py  And it opened the Fake-SMS program window, I chose 2, then entered my Country Code number without + and then my number Without 0, and gives the error "Message not sent! Please Try Again SomeTime Or Use Any Eurpose Based Vpn"
