### ISSUE TITLE
Missing #!/bin/bash

### ISSUE THREAD

**Issue by Comski8** [machine1337/fake-sms#3]
The run.sh script is missing

 `#!/bin/bash`

the console returned 

> ./run.sh: 16: eval: Syntax error: "(" unexpected

when trying to run the script

**Comment by machine1337** [comment]
@Comski8 just type bash run.sh

**Comment by mekb-turtle** [comment]
> @Comski8 just type bash run.sh

yeah but you didn't fix the issue
